import { useEffect, useRef, useState } from 'react';
import type { Source, Video } from '../catalogue/model';
import { fixtures } from '../catalogue/fixtures';
import { readRelays } from '../relay/read';
import { Playback, httpAdapter, unavailablePeerAdapter, type State } from '../playback/playback';
const minutes=(n?:number)=>n?`${Math.max(1,Math.round(n/60))} min`:'Duration unknown';
function Details({video,onBack}:{video:Video;onBack:()=>void}){
 const media=useRef<HTMLVideoElement>(null),heading=useRef<HTMLHeadingElement>(null),player=useRef<Playback|null>(null);
 const [index,setIndex]=useState(0),[consent,setConsent]=useState(false),[state,setState]=useState<State>({phase:'idle',transport:'none',message:'Choose a source. Nothing loads until you consent.'});
 const source:Source|undefined=video.sources[index];
 useEffect(()=>{heading.current?.focus();player.current=new Playback(media.current!,{http:httpAdapter,p2p:unavailablePeerAdapter},setState);const stop=()=>player.current?.stop();window.addEventListener('pagehide',stop);return ()=>{window.removeEventListener('pagehide',stop);stop();};},[]);
 return <section className="details" aria-labelledby="detail-title">
  <button className="back" onClick={onBack}>← Back to catalogue</button>
  <div className="detail-grid"><div><div className="player-frame"><video ref={media} controls playsInline preload="none" aria-label={`${video.title} player`}/><p className="transport">Active transport: {state.transport==='none'?'none':state.transport==='http'?'HTTP':'P2P'}</p></div><p role="status" className={state.phase==='error'?'error':'status'}>{state.message}</p></div>
  <div><p className="eyebrow">{video.origin==='fixture'?'LOCAL FIXTURE':'SIGNATURE-VERIFIED RELAY EVENT'} · {video.category}</p><h1 id="detail-title" ref={heading} tabIndex={-1}>{video.title}</h1><p className="muted">{minutes(video.duration)} · <span className="creator">{video.creator}</span></p>{video.warning!==undefined&&<p className="error">Content warning: {video.warning||'Marked sensitive by its author'}</p>}<p className="synopsis">{video.description}</p>
  {source?<div className="source-panel"><label htmlFor="source">Playback source</label><select id="source" value={index} onChange={e=>{player.current?.stop();setIndex(Number(e.target.value));setConsent(false);}}>{video.sources.map((s,i)=><option key={i} value={i}>{s.type==='http'?`HTTP · ${new URL(s.url).hostname}`:'P2P · WebTorrent (unavailable in this build)'}</option>)}</select>
   {source.type==='http'?<p>HTTP contacts <strong>{new URL(source.url).hostname}</strong>, exposing your IP address to the media host. It uses download bandwidth. This is not peer-to-peer playback.</p>:<p>P2P exposes your IP address to peers and trackers and uses upload bandwidth. Upload caps are not guaranteed. Stop disconnects peers and requests cache cleanup. Browser WebTorrent is unavailable in this build.</p>}
   <label className="consent"><input type="checkbox" checked={consent} onChange={e=>{setConsent(e.target.checked);if(!e.target.checked)player.current?.stop();}}/>I consent to this {source.type==='http'?'HTTP connection':'P2P IP exposure and upload bandwidth'}.</label>
   <div className="actions"><button className="primary" disabled={!consent||state.phase==='connecting'} onClick={()=>{player.current?.start(source,consent,true);media.current?.scrollIntoView?.({block:'center'});}}>{state.phase==='connecting'?'Connecting…':`${state.phase==='error'?'Retry & play':state.phase==='ready'?'Replay':'Play'} via ${source.type==='http'?'HTTP':'P2P'}`}</button><button onClick={()=>player.current?.stop()}>Stop & clear session</button></div>
   <p className="fine">No automatic fallback. A different source requires a new choice and consent. Native player controls handle play, pause and seek.</p>
  </div>:<div className="source-panel"><h2>No playable source</h2><p>{video.origin==='fixture'?'This is an imagined development fixture with no video attached. Return to the catalogue and choose Sintel for the open-movie HTTP demo.':'This event has no supported video URL or torrent. Choose another film or read a different relay.'}</p></div>}
  </div></div>
 </section>;
}
export default function App(){
 const [mode,setMode]=useState<'fixture'|'relay'>('fixture'),[remote,setRemote]=useState<Video[]>([]),[selected,setSelected]=useState<Video|null>(null),[query,setQuery]=useState(''),[category,setCategory]=useState('All films'),[relays,setRelays]=useState(''),[status,setStatus]=useState('No relay connections.');
 const stop=useRef<(()=>void)|undefined>(undefined),lastCard=useRef<string|undefined>(undefined);
 useEffect(()=>()=>stop.current?.(),[]);
 const videos=mode==='fixture'?fixtures:remote;
 const categories=['All films',...new Set(videos.map(v=>v.category))];
 const filtered=videos.filter(v=>(category==='All films'||v.category===category)&&`${v.title} ${v.creator} ${v.description}`.toLowerCase().includes(query.toLowerCase()));
 function switchMode(next:'fixture'|'relay'){stop.current?.();setMode(next);setCategory('All films');setQuery('');}
 function back(){setSelected(null);requestAnimationFrame(()=>document.getElementById(lastCard.current||'browse-title')?.focus());}
 return <><a className="skip" href="#main">Skip to content</a><header><a className="brand" href="./" aria-label="nostr-torrent home"><span className="brand-mark">n<span>◦</span></span>nostr<span className="brand-light">/torrent</span></a><span className="header-note">Independent stories. Open horizons.</span><span className="prototype">PRIVATE PROTOTYPE</span></header>
 <main id="main">{selected?<Details key={selected.id} video={selected} onBack={back}/>:<>
 <section className="hero"><div className="hero-copy"><p className="eyebrow">A DIFFERENT KIND OF CINEMA</p><h1>Good stories.<br/><em>No boundaries.</em></h1><p>A home for independent film, carried by an open network.<br/>Discover the catalogue. Choose how you connect.</p><a className="primary hero-link" href="#browse-title">Explore the collection <span>↗</span></a></div><div className="hero-art" aria-hidden="true"><div className="orb"/><div className="ridge ridge-one"/><div className="ridge ridge-two"/><div className="art-caption">THE OPEN COLLECTION <span>01 / 06</span></div></div></section>
 <section className="catalogue" aria-labelledby="browse-title"><div className="section-heading"><div><p className="eyebrow">YOUR NEXT DISCOVERY</p><h2 id="browse-title" tabIndex={-1}>The collection</h2></div><div className="mode-switch" aria-label="Catalogue source"><button aria-pressed={mode==='fixture'} onClick={()=>switchMode('fixture')}>Local fixtures</button><button aria-pressed={mode==='relay'} onClick={()=>switchMode('relay')}>Relay catalogue</button></div></div>
 {mode==='fixture'?<p className="notice"><span className="dot"/>Local development fixtures · not live relay results. Artwork is generated locally with CSS.</p>:<form className="relay-form" onSubmit={e=>{e.preventDefault();stop.current?.();setRemote([]);setStatus('Reading signed metadata…');stop.current=readRelays(relays.split(/[\s,]+/),v=>setRemote(old=>old.some(x=>x.id===v.id)?old:[...old,v]),setStatus);}}><label htmlFor="relays">Relay URLs (up to 3, wss://)</label><div className="relay-row"><input id="relays" placeholder="wss://your-relay.example" value={relays} maxLength={6144} onChange={e=>setRelays(e.target.value)}/><button className="primary">Read relays</button><button type="button" onClick={()=>stop.current?.()}>Cancel read</button></div><p className="fine">Connect only when you press Read. Relays receive your IP and a video-catalogue query. Signature verification proves authorship, not trustworthiness.</p><p role="status">{status} · {remote.length} verified entries</p></form>}
 <div className="browse-tools"><div className="filters" aria-label="Filter films">{categories.map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div><label className="search"><span aria-hidden="true">⌕</span><input aria-label="Search films" placeholder="Search films, creators…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 <div className="cards">{filtered.map((v,i)=><button id={`card-${v.id}`} data-card className={`card art-${i%6}`} key={v.id} onClick={()=>{stop.current?.();lastCard.current=`card-${v.id}`;setSelected(v);}}><div className="poster" aria-hidden="true"><div className="poster-sun"/><div className="poster-land"/><span className="poster-index">0{i+1}</span><span className="poster-title">{v.title}</span><span className="poster-type">{v.origin==='fixture'?'LOCAL FIXTURE':'VERIFIED SIGNATURE'}</span><span className="card-play">↗</span></div><div className="card-info"><span className="card-category">{v.category} <span>· {minutes(v.duration)}</span></span><h3>{v.title}</h3><p>{!v.sources.length?'No video attached':v.sources.some(s=>s.type==='http')?(v.origin==='fixture'?'HTTP demo · Play available':'HTTP source available'):'P2P unavailable in this build'}</p><p>{v.origin==='fixture'?v.creator:`${v.creator.slice(0,16)}…`}</p></div></button>)}</div>
 {!filtered.length&&<div className="empty"><h3>{mode==='relay'&&!remote.length?'Your relay collection starts here':'No films found'}</h3><p>{mode==='relay'&&!remote.length?'Enter a relay and read signed video metadata. No background connections are made.':'Try a different search or category.'}</p></div>}
 </section></> }</main><footer><span>nostr/torrent <span className="muted">· An open cinema experiment</span></span><span>No account. No watch history. Your choice of transport.</span></footer></>;
}
